# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

project 'Fast IRL.xcodeproj'

target 'FastIRL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FastIRL
  pod 'WebRTC-SDK'
  pod 'Starscream'

end
